### ISSUE TITLE
Load Module file chooser

### ISSUE THREAD

**Issue by dehall** [synthetichealth/module-builder#143]
It would be great if users could load a module directly via file chooser or drag & drop instead of having to open it and copy & paste into our "Paste JSON" popup.

**Comment by arscan** [comment]
Initial implementation complete.  This will probably get moved around as the UI improves, but this is functional and much easier than opening modules and copy/pasting the content into a window and clicking a button.

![screen shot 2018-05-16 at 4 16 37 pm](https://user-images.githubusercontent.com/412901/40142695-582cda18-5927-11e8-8a5e-2486b9a648c6.png)
