### ISSUE TITLE
Add duration to procedure.

### ISSUE THREAD

**Issue by arscan** [synthetichealth/module-builder#145]

**Comment by arscan** [comment]
@jawalonoski @dehall are durations on Procedures required?  [Documentation](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#supported-properties-15) doesn't say optional, but some states in existing module doesn't have a duration.  E.g. `Osteoporosis_Workup` in [Injuries](https://synthetichealth.github.io/module-builder/#injuries).

Same question for [MedicationOrder.prescription.duration](https://synthetichealth.github.io/module-builder/#injuries).

**Comment by jawalonoski** [comment]
No, they are optional. I'll fix the wiki.

**Comment by jawalonoski** [comment]
To clarify -- procedure duration is optional. Right now the engine defaults procedures without durations to 30 minutes.

On the other hand -- Medication prescription duration is not optional. It also isn't currently used by the engine, but the more I thought about it, the more I don't want to make it optional.

**Comment by arscan** [comment]
Note: for Medication prescription, it appears that duration is often not included if `as_needed` is set to `true`.  It is a little problematic for the interface if something is required but not specified in the module already.  Should I just fill in with arbitrary info on load?  Should I have an 'add button' but then once they add it they can't remove it?

**Comment by jawalonoski** [comment]
Maybe duration is only required if as_needed is false or null.
