### ISSUE TITLE
"Add Prescription" on MedicationOrder not working

### ISSUE THREAD

**Issue by dehall** [synthetichealth/module-builder#154]
The link to Add Prescription on MedicationOrder states doesn't seem to do anything, tested on Firefox. The prescription details subpanel works fine when it's already there (ex. in submodule `allergies/severe allergic reaction` state `Mild_Steroid`) but if I remove it from that state I can't re-add it either. No errors shown in console.

**Comment by arscan** [comment]
Fixed and deployed.  This was a bug introduced when I refactored how default values get populated.
