### ISSUE TITLE
Clone/duplicate states

### ISSUE THREAD

**Issue by dehall** [synthetichealth/module-builder#163]
It's fairly common to have two [or more] states in a module that are nearly identical except for some small differences. It would be great if the module builder had the capability to "clone" or duplicate a state, with all state details and transitions intact, so that users don't have to completely build both from scratch.

**Comment by dehall** [comment]
Looks great!

I realized there is the nuance of what if you clone a state that has a transition looping back to itself - can the copy also have a loop back to itself? I don't know if there's an easy or good way to do that. Currently in that situation the copy will transition to the original. I think that's the only special consideration for this feature. If it's a big deal to implement don't worry about it.

Either way, as long as the logic that picks a new state name is guaranteed to be unique I'm good with it.

**Comment by arscan** [comment]
Ahh, yeah I noticed that when cloning new states, but it isn't a big deal in that case.  It is a bigger deal if you have a complex state that you are cloning... having it loop back to itself definitely is what I would expect and it might be something that is easily missed.  I'll address that too.

**Comment by arscan** [comment]
Fixed the bug preventing changing transitions and updated so that loopbacks are maintained in #169.

Deployed the update.  Let me know if you see anything else.  Thanks for checking, I would have missed the importance of that feature.
