### ISSUE TITLE
Save Modules with Local Storage

### ISSUE THREAD

**Issue by arscan** [synthetichealth/module-builder#184]
We could implement Local Storage to allow users to save modules locally, in their browser.  This would be a good first step before attempting to implement a centralized hosting / github integration / etc.

The intent would be to prevent data loss when users close their browser.

**Comment by dehall** [comment]
If this is implemented - it should take advantage of the existing "My Modules", with new additions showing when the module was last saved, and maybe add an (X) button to allow users to remove modules from that list
