### ISSUE TITLE
Allow Observation codes from SNOMED-CT

### ISSUE THREAD

**Issue by notpace** [synthetichealth/module-builder#206]
The `Observation` state allows for LOINC codes to be added, but not SNOMED-CT codes.  There are findings/situations that are not captured in LOINC, e.g., a [positive Murphy's sign](http://browser.ihtsdotools.org/?perspective=full&conceptId1=53566005&edition=us-edition&release=v20180301&server=https://prod-browser-exten.ihtsdotools.org/api/snomed&langRefset=900000000000509007) indicating cholecystitis.

**Comment by dehall** [comment]
The way to do this would actually be to have the observation value be the SNOMED code (also not currently possible but coming soon -- see #205 ). 

Think of the Observation state as a question & answer. The LOINC `codes` indicate the question being asked, for example, LOINC 8480-6 asks "what is the patient's systolic blood pressure?". The "answer" to that question is the "value" of the observation, which could be a number, string, or soon, a SNOMED code.

In this specific case of a positive Murphy's sign, I would suggest the LOINC code to be something like this: https://s.details.loinc.org/LOINC/80271-0.html?sections=Comprehensive   and then you could use the SNOMED code as the value.

**Comment by notpace** [comment]
Makes sense - thanks!

**Comment by dehall** [comment]
FYI - that feature is now live and available

**Comment by notpace** [comment]
Excellent - thanks!
