### ISSUE TITLE
Calculate "remaining %" on distributions

### ISSUE THREAD

**Issue by dehall** [synthetichealth/module-builder#217]
When building up a distributed transition, the final transition is often an "else"-like condition for which the distribution % is just 1 - the sum of the previous distributions. It would be helpful if the system had the ability to set the distribution % to be the remaining %.

More concrete example:
 I create a distributed transition where I have a 0.23% chance of transitioning to state A, a 0.45% chance of transitioning to state B, and whatever the rest is to state C. It would be helpful to have a button on the state C transition that would set it to the remainder, in this case is 99.32%, rather than me having to open up a calculator and manually subtract it out.

**Comment by dehall** [comment]
Other considerations: 
 - this has to work on both distributed and complex transitions that use distributions
 - on "named transitions" aka distributed transitions that use an attribute, the only value that could be used for the calculation is the default value, if provided. If a default isn't provided then the button should be disabled, or at minimum not crash

**Comment by arscan** [comment]
@dehall what is the behavior when no default is provided but the attribute is empty (or whatever triggers the default being used)?  The module builder doesn't support this functionality at all, and it I don't think it is covered in the wiki.

If it is something we want to support everywhere, let's make a new ticket, update the wiki, and update the module builder in separate PR... so we can keep these issues somewhat atomic.

**Comment by dehall** [comment]
@laambrosino @arscan 
Upon closer inspection I think the default value is and should be required.
The java code implements the default as a `double` as opposed to a `Double` which would allow for nulls. If the module builder expects a default value to be provided, and all the current uses of this feature have a default value, then we don't have to worry about instances where the default is not provided, and we shouldn't change anything to make it optional.

**Comment by dehall** [comment]
addressed in #222
