### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by tanejasumit** [synthetichealth/module-builder#234]
Downloaded the zip on 08/29 & trying to run with the command "yarn start" as provided in the Readme.

The command fails with the following error message:
> `Failed to compile.`
> `./src/components/editor/JsonEditor.js`
> `Module not found: Can't resolve 'brace' in 'E:\Development\Workspace\synthea-module-builder-master\src\components\editor'`

Environment details:
- Windows 7 SP1 64-bit
- Yarn v1.9.4
- Node v8.11.4 64-bit

**Comment by jawalonoski** [comment]
Did yarn install the dependencies? See if you have a `E:\Development\Workspace\synthea-module-builder-master\node_modules\brace\mode\json.js` file. Yarn should have installed your dependencies.

**Comment by tanejasumit** [comment]
Hi @jawalonoski 

No I don't have the 'brace' folder at this location. I have:

1. brace-expansion
- index.js
- package.json
- README.md

2. braces
- index.js
- LICENSE
- package.json
- README.md

**Comment by jawalonoski** [comment]
Well, `brace` is one of the listed dependencies in the `yarn.lock` file -- it may have failed into install.

Try `yarn install` and see if you get any error messages.

**Comment by tanejasumit** [comment]
Yes. That worked. Thank you! Closing the issue...
