### ISSUE TITLE
Economic issues

### ISSUE THREAD

**Issue by rlieberthal** [synthetichealth/module-builder#255]
Add annual wellness visit (AWV) price and utilization to reflect the overall cost of visits

- AWVs were introduced into Medicare in 2011 as part of the ACA (http://www.latimes.com/business/lazarus/la-fi-lazarus-obamacare-physicals-20160802-snap-story.html)

- Annual Wellness Visits have a cost of $175 per beneficiary per year (https://www.ajmc.com/journals/issue/2019/2019-vol25-n3/medicare-annual-wellness-visit-association-with-healthcare-quality-and-costs)

- AWVs had a utilization of 7.5% in 2011 rising to 15.6% among Medicare beneficiaries in 2014 (https://jamanetwork.com/journals/jama/fullarticle/2622010)

- AWVs are covered by SNOMED codes 444971000124105 (general) and 456201000124103 (Medicare AWV) (https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=456201000124103)

**Comment by jawalonoski** [comment]
Moved this issue to https://github.com/synthetichealth/synthea/issues/616
