### ISSUE TITLE
Is there a way to suppress DALY and QALY observations?

### ISSUE THREAD

**Issue by nikhilrowland** [synthetichealth/module-builder#316]
After combing through the observations csv for my model I found that the vast majority of observations are DALY and QALY observations. I assume Synthea generates these automatically because they do not have an enounter ID associated with them. I was wondering if there was anyway to not generate these observations to reduce the file size.

**Comment by jawalonoski** [comment]
There is no command line option to do that.

Your choices are (1) filter out the data after export, or (2) change some code.

https://github.com/synthetichealth/synthea/blob/d4af94570aba5ba9b199d0071b6ca8be0763e441/src/main/java/org/mitre/synthea/export/CSVExporter.java#L517-L518

```Java
    String[] gbdMetrics = { QualityOfLifeModule.QALY, QualityOfLifeModule.DALY,
        QualityOfLifeModule.QOLS };
```
Change the two lines above to be:

```Java
    String[] gbdMetrics = {};
```

Then recompile and rerun and there will be no quality or disability adjusted life year data.

**Comment by nikhilrowland** [comment]
Thanks!
