### ISSUE TITLE
Update state references on state rename

### ISSUE THREAD

**Issue by kjmahalingam** [synthetichealth/module-builder#44]
When a state is renamed, all references to the previous state name are maintained. These references should all be updated to the new state name, instead.

**Comment by dehall** [comment]
There's more to this than just transitions, you can reference certain state types in a `reason`, or `condition_onset` or `medication_order`, etc. That's part of what made this so tricky. Transitions gets you most of the way there and makes the UI look nice but you can still have dangling references after renaming something

**Comment by arscan** [comment]
Ok, see #125 

I think I got all of them.  I did a search for "State_Name" in the GMF state page.

Question: what if we delete a state?  I suppose we should delete the referenced attribute/reason/etc?  Or should we set it to blank?

**Comment by arscan** [comment]
Also, PriorState transitions need this too?

**Comment by kjmahalingam** [comment]
Deleting the referenced attribute is the best approach, I think, if deleting a state.

If you mean PriorState conditionals, then yes, I think those will need this update as well. I will make a comment about this in #125.

**Comment by arscan** [comment]
Alright, hold off on that PR until I do those 2 things.  Should just take a few minutes.

**Comment by arscan** [comment]
Already fixed.
