### ISSUE TITLE
Add visual warning for disconnected states

### ISSUE THREAD

**Issue by kjmahalingam** [synthetichealth/module-builder#52]
It is possible for a state to be implemented without being connected to any other states in the module. Although this is technically allowed, this is not desirable. There should be some visual indication in the graph that a state is completely disconnected.

**Comment by arscan** [comment]
![screenshot-2018-6-27 synthea generic module builder](https://user-images.githubusercontent.com/412901/41977773-3a015af4-79ee-11e8-8512-19c6be6b718a.png)

Not exactly a visual warning in the graph, but I added a generic method to detect and report on problems with the current module.  This includes checking for states that cannot be reached.
