### ISSUE TITLE
Implement direct JSON editing

### ISSUE THREAD

**Issue by kjmahalingam** [synthetichealth/module-builder#69]
Certain users might attempt to edit the JSON of a module directly, in addition to editing the module through the editors. This should be possible.

**Comment by arscan** [comment]
![screenshot-2018-6-27 synthea generic module builder 1](https://user-images.githubusercontent.com/412901/41978089-04726616-79ef-11e8-93b7-22424c22e5e3.png)

Implemented, with code highlighting and collapsible sections.
